# general cover
cover: /css/images/background.jpeg

# authors
authors:
  user:
    name:
    username:
    avatar: /css/images/avatar.png
    shortbio:
    longbio:
    location:
    website:
    cover: /css/images/background.jpeg
    social: # Add social network profile links
      facebook:
      twitter:
      google-plus:
      github:
      instagram:
      flirck:
      linkedin:
      steam:
      tumblr:
      pinterest:

#opengraph
twitter_profile:
googleplus_profile:
fb_admins:
fb_app_id:

lightbox: true
fitvids: true

excerpt_link: Read More

#analytics
google_analytics:

# Miscellaneous, check out your root config in _config.yml
rss: /atom.xml
