# general cover
cover: /css/images/background.jpeg

# authors
authors:
  user:
    name: Another User
    username: myUser
    avatar: /css/images/avatar.png
    shortbio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id.'
    longbio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id. <br><br> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id.'
    location: Earth, Milky Way
    website: http://andresgodinez.me/hexo-theme-casperify/
    cover: /css/images/background.jpeg
    social: # Add social network profile links
      facebook: https://facebook.com/
      twitter: https://twitter.com/
      google-plus: https://plus.google.com/
      github: https://github.com/
      instagram: https://instagram.com/
      flirck: https://flirck.com/
      linkedin: https://linkedin.com/
      steam: https://store.steampowered.com/
      tumblr: https://tumblr.com/
      pinterest: https://pinterest.com/

#opengraph
twitter_profile:
googleplus_profile:
fb_admins:
fb_app_id:

lightbox: true
fitvids: true

excerpt_link: Read More

#SEO
google_analytics:

# Miscellaneous
rss: /atom.xml
